# This workflow will build a Java project with Maven.
name: build

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment
        uses: actions/setup-java@v3
        with:
          java-version: 19.0.1+10
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn -B clean verify
      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: |
            target/*.asc
            target/*.jar
            target/*.pom
          retention-days: 1
